name: fripesfinderv2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'  # Contrainte SDK ajoutée

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  flutter_animate: ^4.1.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_auth_web: ^6.0.3
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  cached_network_image: ^3.2.3
  image_picker: ^1.2.0
  google_maps_flutter: ^2.2.1
  geolocator: ^14.0.2
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  badges: ^3.1.1
  flutter_js: ^0.8.5  # Ajouté pour remplacer js: ^0.7.2
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  google_maps_cluster_manager: ^3.0.0+1
  logger: ^2.0.2
  google_maps_flutter_web: ^0.5.14+2
  file_picker: ^10.3.3
  google_sign_in: ^6.1.5  # Utilise la dernière version stable


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
